image: atlassian/default-image:2

pipelines:
  default:
    # - step:
    #       name: Enviroment Setup
    #       script:
    #         - mkdir build
    #         - apt install <name>    
            #  - pwd
    - step:
        name: "Build"
        script:
          - echo "Everything is awesome!"
          - zip -r weatherapp.zip *
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $APPLICATION_NAME
              COMMAND: 'upload-only'
              ZIP_FILE: 'weatherapp.zip'
              S3_BUCKET: $S3_BUCKET
    #  - step:
      #       name: Test
      #       script:
      #         - npm run test 
      #       artificats:
      #         - test/**     
    #- step:
    #    name: "Deploy to test"
    #    deployment: Test
    #    trigger: automatic
    #    script:
    #      - echo "Deployment to test!"
    #      - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
    #        variables:
    #          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    #          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    #          AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    #          APPLICATION_NAME: $TESTAPPLICATION_NAME
    #          COMMAND: 'deploy-only'
    #          ENVIRONMENT_NAME: $TEST_ENV_NAME
    #          WAIT: 'true'
    - step:
        name: "Deploy to Prod"
        deployment: Production
        trigger: automatic
        script:
          - echo "Deployment to Production!"
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.2.3
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              APPLICATION_NAME: $APPLICATION_NAME
              COMMAND: 'deploy-only'
              ENVIRONMENT_NAME: $ENV_NAME
              WAIT: 'true'
